### ISSUE TITLE
Authentication does not seem to work using API Token

### ISSUE THREAD

**Issue by maknotavailable** [paynl/nodejs-sdk#9]
```
  var Paynl = require('paynl-sdk');
  Paynl.Config.setApiToken("XXX");
  Paynl.Config.setServiceId("XXX");
  Paynl.Paymentmethods.getList().forEach(
  	function(paymentmethod) {
  		console.log(paymentmethod.id + ' ' + paymentmethod.visibleName);
  	}
  )
  .catch(error => {
  	console.error(error);
  });
```
Results in:
`TypeError: 'map' is not a function`

I am able to run this request in Postman using a handshake, and via the test API using the token. However, it does not work using the NodeJs SDK (1.1.4). It seems that the authentication is not going through, as the getList() is empty.

The error messages could be improved, to help get a better understanding for what exactly is going wrong. 

With that in mind, any ideas what the issue here could be ?

**Comment by woutse** [comment]
I tested this, and it seems to be working fine in 1.1.4. So could you please e-mail us on support@pay.nl, then we'll check the auth data you are using (use `webshop nodejs sdk` in subject).
